name: build-and-push
on:
  push:
    tags: ['v*.*.*']
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # needed for GHCR
    steps:
      - uses: actions/checkout@v4

      # set image coords
      - name: Set image
        id: meta
        run: |
          OWNER="${GITHUB_REPOSITORY%/*}"
          IMAGE="ghcr.io/${OWNER}/portfolio-tracker"
          if [ "$GITHUB_REF_TYPE" = "tag" ]; then
            TAG="$GITHUB_REF_NAME"
          else
            TAG="main"
          fi
          echo "image=${IMAGE}" >> $GITHUB_OUTPUT
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./portfolio-backend
          platforms: linux/amd64       # keep x86 for max compatibility
          push: true
          tags: |
            ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.tag }}
            ${{ steps.meta.outputs.image }}:latest